# Generated by Django 3.0.6 on 2020-05-15 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('comment_body', models.TextField()),
            ],
        ),
    ]
