# Generated by Django 3.0.6 on 2020-05-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=20)),
                ('released', models.CharField(max_length=255)),
                ('runtime', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=255)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('box_office', models.CharField(max_length=255)),
                ('production', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('comments', models.ManyToManyField(to='core.Comment')),
            ],
        ),
    ]
