# Generated by Django 3.0.6 on 2020-05-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200516_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('total_comments', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
