# Generated by Django 3.0.6 on 2020-05-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200517_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='top',
            name='start_date',
        ),
    ]
