# Generated by Django 3.0.6 on 2020-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200516_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='core.Comment'),
        ),
    ]
