# Generated by Django 3.0.6 on 2020-05-17 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='top',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
